### ISSUE TITLE
Inform a user a shortcut with given trigger already exists

### ISSUE THREAD

**Issue by DCzajkowski** [quickwords/quickwords#32]
## Introduction
When users create a snippet they have to assign a trigger that causes a snippet to be replaced. For example, when you want to display current date, you may want to assign `;date` as a trigger.

## Problem
When a user has one snippet in place, and want to create a second one with the same trigger, there is no stopping of that.

## How to solve this (overview)
There should be either an indication saying "This trigger is already in use" or some visual feedback informing a user this trigger is already in use.

## How to solve this (technical)
In this directory: [src/renderer/windows/main](https://github.com/quickwords/quickwords/tree/master/src/renderer/windows/main) there are all the files that are creating the frontend of the app. Quickwords' frontend is written in Vue.js, so it should be familiar to anyone who have worked with this framework. The #56 shows how activating works in the new release.

Very primitive version of the UI is available via [CodePen](https://codepen.io/DCzajkowski/pen/xjMZyY). You can use this as a learning opportunity to familiarise yourself with the UI in its simplest form. (This UI is the very early version and it is not the same as the in-app UI. It should be used just as a reference)

---

We are looking for well-thought PRs, preferably with screenshots, showing the new change in both light and dark theme.

**Comment by Warzecha** [comment]
I'd like to work on that ;)

**Comment by DCzajkowski** [comment]
It's all yours! :)

**Comment by DCzajkowski** [comment]
Look at #56 for how activating works in the new release.
