### ISSUE TITLE
Make the About Quickwords item in menu open the About window

### ISSUE THREAD

**Issue by DCzajkowski** [quickwords/quickwords#44]
![](https://i.imgur.com/MVEc5hD.png)

The _About Quickwords_ button is not opening the about window.

**Comment by b-dashyan** [comment]
Hey man, I can give this a try. Which version of node are you using for this project?

**Comment by DCzajkowski** [comment]
v8.3.0. Thanks! If you have any questions feel free to ask :)
Here are the setup instructions: https://quickwords.co/docs/installation.html#manual-build

**Comment by b-dashyan** [comment]
I'm trying to run it but nothing happens. I followed the steps in the documentation and checked that I'm running v8.3, I have no visible errors in the console. When I run `npm run start` I can see that a new icon appears in the dock but then it disappears very fast. Not sure what to do here?

**Comment by DCzajkowski** [comment]
It is a desired behaviour. Open the app from your menu bar at the top-right. 😉

**Comment by b-dashyan** [comment]
Oh right, didn't notice that 😅 seems the about page is already working though?

![Screenshot](https://i.imgur.com/obuArQv.png)

**Comment by DCzajkowski** [comment]
It works when you open it from the menu on the right, not when you open it from the menu on the left (open snippets/preferences window to see the menu on the left)

**Comment by DCzajkowski** [comment]
It's this line that is causing the window not to open: https://github.com/quickwords/quickwords/blob/master/src/main/helpers.js#L24

I have not seen any of this code in a long time, so any improvements are welcome 😉

The function name should be probably renamed to something more descriptive: https://github.com/quickwords/quickwords/blob/master/src/main/index.js#L68

**Comment by DCzajkowski** [comment]
The function name should be probably renamed to something more descriptive: https://github.com/quickwords/quickwords/blob/master/src/main/index.js#L68

**Comment by DCzajkowski** [comment]
Note to myself: The font on your screenshot seems off.

For me it looks like this: ![](https://i.imgur.com/aIXmf1I.png)

**Comment by DCzajkowski** [comment]
I want to make a release soon, so I need to have it fixed now. That's why I've made #53. Sorry for interrupting your work and thanks for your willingness to help 👊
