### ISSUE TITLE
Currently replacements won't work if the `C` key is somewhere else or when `cmd+c` is not a shortcut for pasting

### ISSUE THREAD

**Issue by DCzajkowski** [quickwords/quickwords#46]
To make a snippet replacement, currently we are simulating `cmd+v` on macOS and `ctrl+v` on Linux and Windows. This won't work, when the `v` key in the current keyboard layout is not where it is in the US QWERTY layout. It also won't work, if `cmd+v`/`ctrl+v` is not an actual shortcut for pasting.

## Possible solution
To solve the first issue is pretty easy. We have to find where the `v` key is in current layout by running the `getKeyMap()` on the native-keymap module.

Solving the second issue gets rid of the first one. We have to simulate global OS `paste` event. How to do this? We don't know. **For the person that finds the solution we are going to send our awesome Quickwords stickers** and you are going to land in our README file  😉

**Comment by eugeniumegherea** [comment]
I think it's possible to emit OS level key combinations using [this](https://www.semicomplete.com/projects/xdotool/). It states that it works on both linux and mac. I searched the same for Windows and it does seem to be kinda easy to do in C++ or Python. But, I don't know how to integrate these in electron build/install process as they are native dependencies that are need to be build on client machine (at least for linux and mac)

**Comment by DCzajkowski** [comment]
We can always try to bridge to C++ with node-gyp, but using different plugins for Windows and different for the other two OSs seems like a nightmare to maintain. 😕

**Comment by wastegaby** [comment]
Hi,

Not sure I understand correctly the second part of this issue but if cmd / ctrl + v is not the current OS shortcut for pasting why not to provide a Preferences Menu where users could set shortcuts as set in their current OS / machine ? Obviously this setting could have a default value to the most common value (I think so) cmd / ctrl + v shortcut.

**Comment by DCzajkowski** [comment]
@wastegaby That's a great idea! We are going to put this in our backlog and you can follow the progress here: #55. If you want to get stickers, just send me an email 😉

**Comment by wastegaby** [comment]
Glad to contribute.
I send you an email soon :-)
