### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by DCzajkowski** [quickwords/quickwords#48]
We need some testing. Some have been written in #29, but they are not the best.

### What we need:
- integration tests with Cypress/Spectron
- unit tests with Jest or Mocha
- ESLint and Prettier

**Comment by DCzajkowski** [comment]
Anything meaningful that gets us closer to 100% coverage is eligible for stickers 😉

**Comment by minimalistdev** [comment]
How I will receive the stickers, can I work on this per part, starting with ESLint and Prettier, will be nice create another issue :)

**Comment by ItamarShDev** [comment]
will be happy to take this

**Comment by DCzajkowski** [comment]
@cfsbsi You can absolutely work on the Prettier part. We want to make this project easier to maintain so anything can help. We already have ESLint set up, but any tweaks are welcome.

@ItamarShDev Do you want to work on tests? If so, make sure to familiarize yourself with #29. Any improvements to these horrible tests are welcome 😉
