### ISSUE TITLE
Setup Travis CI so that it compiles apps for macOS and Linux

### ISSUE THREAD

**Issue by DCzajkowski** [quickwords/quickwords#49]
Currently Travis is just running tests. We want it to compile out `.dmg` and `.AppImage`. Anything that gets us closer to that goal is eligible for a sticker.

P.S. Linux version is still in the works and it may not work as expected. If you can bring us closer to releasing the Linux version (even without the Travis setup) we would really appreciate that with a sticker 😉

**Comment by minimalistdev** [comment]
I would like to work on this

**Comment by DCzajkowski** [comment]
Awesome! 💃

**Comment by DCzajkowski** [comment]
If you need an access to our Travis account, let me know 😉

**Comment by minimalistdev** [comment]
please, yes

**Comment by DCzajkowski** [comment]
I've sent you an e-mail :)

**Comment by minimalistdev** [comment]
Hi, I created the PR #54 but someone with travis access should setup somethings below:

- Create a ssh key

- Add on https://github.com/quickwords/quickwords/settings/keys

- Encrypt the key follow this
https://github.com/travis-ci/travis-ci/issues/2457
Using travis cli with the command: travis encrypt ~/Desktop/id_rsa --add deploy.api-key

- Set on travis in settings env variables the name GH_TOKEN on 
https://travis-ci.org/quickwords/quickwords/settings

- Create tag and push

should work, this is the example: https://travis-ci.org/cfsbsi/quickwords

this take some time and I didn't deliver the dist folder, if u can create a task for me see that please.

And any question about the travis setup let me know

**Comment by DCzajkowski** [comment]
Great work! Thanks for your PR and instructions. I will try to get my head around it as soon as possible. In the meantime you can send me an address you want me to send stickers to (via e-mail or my website)(if you want them, of course 😉). Thank you for the contribution and I will be back at most by the end of this week.

**Comment by DCzajkowski** [comment]
I think we'll be using GitHub actions for that.
