### ISSUE TITLE
Create a new option in preferences, to set up a paste shortcut

### ISSUE THREAD

**Issue by DCzajkowski** [quickwords/quickwords#55]
## The problem
Currently replacements won't work if the `C` key is somewhere else or when `cmd+c` is not a shortcut for pasting (see: #46). To solve this, we can create a new field in the preferences window to set-up your shortcut for pasting (see: https://github.com/quickwords/quickwords/issues/46#issuecomment-429517891, thanks @wastegaby).

## The solution
1. Create a new label in the preferences window saying "Shortcut for Pasting".
2. When clicked, listens for a shortcut to be inserted the same way IntelliJ works (just a label that show the currently-selected shortcut and whenever something is pressed it listens for these keys and displays them).
3. Translate the shortcut to the US QWERTY keyboard layout
4. Save the shortcut in the Electron Store
5. Use the saved shortcut whenever a snippet replacement occurs

## Bonus
**Whoever comes up with a working prototype we are going to send our awesome Quickwords stickers to.** If you need any help, or want to cooperate (even via Hangouts or what have you) we are down! Let's do this!

**Comment by evanre** [comment]
Hey, guys, sorry for stupid question. But how to use it? I've installed it and provide all permissions. But how to expend this abbreviations?

**Comment by DCzajkowski** [comment]
Hi @evanre, if something is not working, we can arrange a Hangouts/Skype call and assess what's and why is not working. If you don't want to talk, you can write me an email and I can explain everything. My email address is dare.czajkowski on gmail.

**Comment by evanre** [comment]
Wow, it works! I just relaunched the app (after first launch and given it permissions) and now it works as well. Thank you! ❤️

**Comment by DCzajkowski** [comment]
Awesome! Great to hear that 🎉
