### ISSUE TITLE
Freeze on mojave 10.14.0 and 10.14.1

### ISSUE THREAD

**Issue by ManUtopiK** [quickwords/quickwords#57]
I've migrated my macbook from High Sierra where everything worked well to Mojave 10.14.0.
On each click (right or left), the screen freeze 20 seconds about. If I quit Quickwords, it's OK.
I updated to 10.14.1 and the same thing happen.

**Comment by DCzajkowski** [comment]
I am sorry to hear that. Unfortunately I am not running Mojave yet, but my co-creator of Quickwords @gtluszcz is and he confirms something bad is happening. We will investigate 😉

**Comment by DCzajkowski** [comment]
Can you please confirm, that after turning off Quickwords the problem does not persist?

**Comment by DCzajkowski** [comment]
We are planning to update iohook — the underlying library for handling key presses — with hope it will fix that. I will try to do that this weekend and make a new release. Unfortunately, as this problem is not happening on my computer, I won't be able to test that in any way.

If you are willing, I can send you a new release and you can test it before anyone else gets an update. Would that be ok with you?

**Comment by ManUtopiK** [comment]
I've just trying again on a fresh install of Mojave 10.14.1 on a mac mini and got the same behavior : freeze on each click.

Yes, I can test a new release. Happy to help you!

**Comment by DCzajkowski** [comment]
Awesome! I'll be back soon 😉

**Comment by DCzajkowski** [comment]
Hey. So I've managed to update all of the dependencies and have bumped the version to v0.1.2. Let me know, if that has resolved the issue 😉

Here is the link: https://drive.google.com/open?id=1pItkGX81HyP-cs52iqmBSZtqtZdj-quE

P.S. It may be required to re-grant the permissions. If that happens, remember to close and open the app for the changes to take place 🙂

**Comment by DCzajkowski** [comment]
Hey, do you have any update on that @ManUtopiK?

**Comment by ManUtopiK** [comment]
Oups, sorry!
I've installed your update 26 days ago and everything works fine.
I told myself that I would test 2-3 days before responding to you to be sure everything is good but I forgot...
So, I tested your update during 26 days and I never got a freeze. Good job 😃
