### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by diomed** [quickwords/quickwords#58]
hey

how's it going with windows version of app?
I've been hoping for this for quite some time now.

**Comment by DCzajkowski** [comment]
Hey, thank you for your interest in Quickwords. Unfortunately, at the moment we don't have much time on our hands as we are both working and studying. There is an open PR (#26) that is nearly working on Windows and just needs some polish and love. We really wanted this version to come out as soon as possible, but our motivation faded a little, as we don't use Windows ourselves.

It would be amazing if someone could install Quickwords from this PR, polish it so that we'd have to just make a release. If noone like this comes about, we will have to take this into our own hands, but end of February is the closest date we'd have time to do so.

**Comment by diomed** [comment]
I see there's some progress here. Is win version to be expected soon?

**Comment by DCzajkowski** [comment]
At this moment we are trying to install npm and all required packages on Windows and it is taking us a few hours already. We will keep you updated!

**Comment by DCzajkowski** [comment]
Hey, we have just built a first 0.2.0 version for Windows. Would you be willing to test it out @diomed? If yes, please send me a message from [darek.dev](https://darek.dev) so that I can send you the `.exe` 😊

**Comment by diomed** [comment]
I get this error saying 
`Quickwords\resources\app.asar`

The archive is either in unknown format or damaged

**Comment by DCzajkowski** [comment]
Hey, we have had that reported to us once by a tester. It happened when booting up Windows. Apparently, our autolaunch is not working as expected. We have heard though, Quickwords was still working in the Tray and things worked as expected. Can you confirm?

**Comment by diomed** [comment]
yes, that's it.

also, take a look @ this file:

[English_AutoCorrections.txt](https://github.com/quickwords/quickwords/files/2961207/English_AutoCorrections.txt)

would be great if we could somehow be able to include such file so it fixes already existing stuff.
updating over the  ui is kinda a lot of work.

**Comment by DCzajkowski** [comment]
It's technically possible to achive that already. Just convert the file to a specific json and paste it into the config file

**Comment by diomed** [comment]
could you please incorporate that file?
or maybe make some gist on github out of it,
so one could use it properly

**Comment by diomed** [comment]
where are snippets stored, exactly?

**Comment by DCzajkowski** [comment]
> where are snippets stored, exactly?

Wherever the default App Data directory is located. On macOS it is in `/Users/<User>/Library/Application Support/Quickwords/config.json`. Maybe try searching for a `Quickwords/config.json` on your system.

**Comment by DCzajkowski** [comment]
Look for a directory the app was installed in. It should be somewhere in there

**Comment by diomed** [comment]
it's in 

`Users/Username

/AppData/Roaming/Quickwords`

I've made config.js publicly available here:
https://gist.github.com/diomed/27c0fd285052ffd90a74f02514853d3e

so anyone who wants can get it. 
would be cool if you included it in program itself, however, but that's up to you.
or maybe mention it's existence on main repo page.

**Comment by diomed** [comment]
is there gonna be update for windows, that removes that annoying error :P

**Comment by DCzajkowski** [comment]
Hey, both me and @gtluszcz don't use Windows, so we abandoned the development for this OS. If anyone wants to make PRs and improvements, they are more than welcome ☺️
