### ISSUE TITLE
Blocking internet connection breaks Quickwords

### ISSUE THREAD

**Issue by ghost** [quickwords/quickwords#59]
Upon executing a snippet, Quickwords attempts to connect to Google and cloudfunctions.net. Blocking these connections results in a JavaScript error that renders the app unusable.

I appreciate the attention to privacy and security in the Quickwords manual, but would it be possible to use the app without connecting to the internet? Thanks!

![screen shot 2019-01-26 at 2 08 41 pm](https://user-images.githubusercontent.com/46864481/51789965-4e98b900-2176-11e9-9796-693b0128af13.png)

![screen shot 2019-01-26 at 2 13 50 pm](https://user-images.githubusercontent.com/46864481/51789966-4f314f80-2176-11e9-9439-866f2df2929f.png)

![screen shot 2019-01-26 at 2 22 33 pm](https://user-images.githubusercontent.com/46864481/51789967-4f314f80-2176-11e9-8de0-a1fbfdfde05a.png)

**Comment by DCzajkowski** [comment]
Yeah, the code behind this is [here](https://github.com/quickwords/quickwords/blob/master/src/main/modules/Analytics.js) and [here](https://github.com/quickwords/quickwords/blob/master/src/main/modules/SnippetsManager.js#L128).

It is just analytics. We are just sending this information:
- randomly generated number upon app installation,
- is the snippet using regex,
- is the snippet js or plain text,
- version of the app.

I agree this is something users would not expect and we should give an option, to disable this. We really value privacy, but at the same time we wanted to see, how many people are using the app. Without this number, we really lacked motivation, as we didn't have any clue who, and more over does anyone, use the app. If you want, you can add an option in a PR. We will do it ourselves, if noone does it, but we are very busy at the moment.

**Comment by ghost** [comment]
That makes a lot of sense! Thanks for making a great app!
