### ISSUE TITLE
disk image couldn't be opened (but it did anyway)

### ISSUE THREAD

**Issue by CouldBeThis** [quickwords/quickwords#63]
Hello,

I am not sure if this is useful info to you or not. Mac Catalina 10.14.6

Downloaded from gh and got these popups in this order:

![Screen Shot 2020-12-03 at 7 48 35 AM](https://user-images.githubusercontent.com/53547181/101020458-8a53f500-353c-11eb-92e1-39145bb225f8.png)

#2 always happens from gh but #1 is unusual. 

Anyway program looks to have installed/opened properly.

So maybe no problem. :)

**Comment by DCzajkowski** [comment]
Indeed, #​1 is unusual and I have never seen it 🙈 I hope this is the only case this has appeared for anyone. Thanks for letting me know! :)
